import { Sparkles } from "lucide-react";

import { apiErrorMessage } from "@/api/client";
import { useAiInsights } from "@/api/hooks/useAi";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardBody, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "@/store/toast";

const PRIORITY_TONE = { high: "danger", medium: "warning", low: "info" } as const;

/** "AI SEO Advisor" card — turns any analysis context into a prioritized,
 *  AI-written action plan. Shared by the All-in-One and Site Report pages. */
export function AiAdvisor({ context, ready }: { context: Record<string, unknown>; ready: boolean }) {
  const ai = useAiInsights();
  const run = () => ai.mutate(context, { onError: (e) => toast.error(apiErrorMessage(e)) });

  return (
    <Card className="border-[color:var(--section)]">
      <CardHeader>
        <div className="flex flex-wrap items-center justify-between gap-2">
          <CardTitle>
            <span className="inline-flex items-center gap-2">
              <Sparkles size={16} className="text-[color:var(--section)]" /> AI SEO Advisor
            </span>
          </CardTitle>
          <Button size="sm" onClick={run} loading={ai.isPending} disabled={!ready}>
            {!ai.isPending && <Sparkles size={14} />}
            {ai.data ? "Regenerate" : "Get AI suggestions"}
          </Button>
        </div>
      </CardHeader>
      <CardBody>
        {ai.isPending ? (
          <Skeleton className="h-40 w-full" />
        ) : ai.isError ? (
          <p className="text-sm text-danger">{apiErrorMessage(ai.error)}</p>
        ) : ai.data ? (
          <div className="space-y-4">
            {ai.data.summary && <p className="text-sm text-text">{ai.data.summary}</p>}
            <ul className="space-y-2.5">
              {ai.data.suggestions.map((s, i) => (
                <li key={i} className="rounded-md border border-border p-3">
                  <div className="flex items-start justify-between gap-2">
                    <p className="text-sm font-medium text-text">{s.title}</p>
                    <Badge tone={PRIORITY_TONE[s.priority] ?? "info"}>{s.priority}</Badge>
                  </div>
                  {s.detail && <p className="mt-1 text-sm text-text-muted">{s.detail}</p>}
                </li>
              ))}
            </ul>
            <p className="text-xs text-text-muted">Generated by {ai.data.model}.</p>
          </div>
        ) : (
          <p className="text-sm text-text-muted">
            Turn this analysis into a prioritized, AI-written action plan — specific fixes ranked by impact.
          </p>
        )}
      </CardBody>
    </Card>
  );
}
